# Generated by Django 6.1.1 on 2026-09-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recordings',
            new_name='Recording',
        ),
    ]
